apiVersion: apps/v1
kind: Deployment
metadata:
  name: jag-deployment
  labels:
    app: jagapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jagapp
  template:
    metadata:
      labels:
        app: jagapp
    spec:
      containers:
      - name: jag-container
        image: jmuniyap/myapp33:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jagapp-lb
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: jagapp 
