# Workflow to deploy the docker_img
name: deploy_docker_img
on: 
  workflow_run:
    workflows: ["build_docker_img"]
    types:
      - completed

jobs:
  deploy:
    runs-on: jag-devops
    environment: prod
    steps:
      - name: check out the code
        uses: actions/checkout@v4.1.1
      - name: deployment using kubernetes
        run: |
          kubectl apply -f deployment.yml
          kubectl get deployments
