# Workflow to deploy the docker_img using playbook
name: deploy_playbook 
on: push


jobs:
  deploy:
    runs-on: jag-devops
    steps:
      - name: check out the code
        uses: actions/checkout@v4.1.1
      - name: deployment using kubernetes
        run: |
          sudo ansible-playbook -i /root/inv /root/play.yml
